### ISSUE TITLE
[Feature Request] "MSRP" Field

### ISSUE THREAD

**Issue by royaltongue** [icbestCA/giftmanager#12]
So buyers can have a general idea of the prices of the gift ideas, it would be nice to have an optional "MSRP" field that the user could fill in while creating the idea

**Comment by icbestCA** [comment]
Hello, I've been considering this feature for a time. The problem is that it is a bit taboo to talk about money when it come to gift. So if you're ok with it I will add it but will be a bit more hidden in a collapsing menu. Is this ok for you? Do you have another ideas?

**Comment by royaltongue** [comment]
Considering the person in question is about to spend money on you anyway, I don't see the issue with listing prices. If anything, it makes easier for the buyer to "avoid" presents that could be outside of their price range

**Comment by icbestCA** [comment]
Now added the feature, hope it work for you.
