### ISSUE TITLE
[Feature Request] Allow multiple overlapping Secret Santa pools

### ISSUE THREAD

**Issue by janssenvdh** [icbestCA/giftmanager#14]
First of all, I love this app! Thank you so much for sharing it.

I draw names on both sides of my family. It would be great if there could be multiple, overlapping pools of participants for Secret Santa. I suggest the pools be named in a customized way during participant selection, such as "Smith" and "Jones".

A possible workaround is to use a separate instance for each family (easy with Docker), but then the set of gift ideas would not be shared between them.

I was able to create effectively separate _non-overlapping_ pools by checking the box for different names each time (e.g., one pool for adults and another for children), but the instructions get overwritten in `santa_inst.txt` (although that can be worked around by listing each set of instructions in the instructions field during the last setup). However, with only one `assigned_user` field in the JSON file, any _duplicate_ participants will overwrite the assignments for earlier pools.

**Comment by icbestCA** [comment]
Hello! I've made a new commit you can now add different pools with each different instructions. Also updated the docker image! Hope it will work well for you! Thanks

**Comment by janssenvdh** [comment]
This works perfectly. Thank you so much!
