### ISSUE TITLE
[Feature Request] Backup Restoration On Fresh Container

### ISSUE THREAD

**Issue by royaltongue** [icbestCA/giftmanager#15]
When updating the Docker container, the `users.json` and `ideas.json` get reset to their defaults. With the new backup system in place, it would make sense to check for any backup files upon container creation. If any exist, restore the latest backup taken. If none are found, create the default file.

EDIT: Also thanks for all the work :) And sorry for all the issues I've been opening ;P

**Comment by icbestCA** [comment]
No problems, I've implemented the feature, make sure to read the docs, the run command changed. Now it will scan the host machine directory for the latest files, it none exist it will be downloaded from r2.icbest.ca (cloudflare storage) to get the originals.
Thanks for contributing to the project!!
