### ISSUE TITLE
[Bug] Secret Santa icon with link no longer appears

### ISSUE THREAD

**Issue by janssenvdh** [icbestCA/giftmanager#16]
The gift icon `secret-santa.svg` no longer appears when Secret Santa pools have been set up.
![secret-santa](https://github.com/user-attachments/assets/b71f55af-1149-4c55-867b-15779e6dc22e)

**Comment by icbestCA** [comment]
Can I get more infos? The button only show when a user is registered in a pool. Can you check into the json file if the user is correctly assigned to someone, if yes, then it's probably a problem with the icon location or html not detecting the assignation.
Thanks.

**Comment by janssenvdh** [comment]
Yes, there are entries in the `assigned_users:` and `pool_name:` fields in the json file. 

I'm using the docker image from 2024-09-08.

**Comment by janssenvdh** [comment]
I pulled the docker image from 2024-09-12 and the icon has returned.
