### ISSUE TITLE
[Feature Request] Manually Ordering "My Ideas" List

### ISSUE THREAD

**Issue by royaltongue** [icbestCA/giftmanager#18]
Allow manual ordering of a user's Ideas list to show "priority" of each gift

**Comment by icbestCA** [comment]
Hi! I really like the idea. However, I was wondering how we might organize it. Would we incorporate a numbering system for ordering? Alternatively, we could mark certain ideas as “absolutely want” to prioritize them at the top of the list, instead of numbers for all of them. What do you think?

**Comment by royaltongue** [comment]
Personally, I would want to the whole list individually rather than the "absolutely want" system you mentioned.

As far as UI goes, I think an up/down arrow to move one space in either direction, plus a grabbable icon between them to freely move the item throughout the list. When new items are created, I think it makes sense to default to putting it at the end of the list.

**Comment by icbestCA** [comment]
Hello, I've competed your idea of ordering here is how it works: Only on the my_ideas page you can order the ideas YOU added to your list, using a drag and drop feature. Only on this page you will see the ordering numbers. When viewed by others, they will see the correct order without the numbers, and the ideas added by other members will appear always under your ordering.
