### ISSUE TITLE
App forces landscape

### ISSUE THREAD

**Issue by Robert-litts** [icbestCA/giftmanager#2]
When opening the app on my Android, the app forces me to rotate to landscape before I can interact. I saw your comment on Reddit that says the "ideas list" is too compressed & may require alternative layout. 

For my use case, portrait mode should be the default.

![giftmanager_rotate](https://github.com/user-attachments/assets/41899cb1-8c1b-40ec-a331-c1eef92f504d)

**Comment by icbestCA** [comment]
problem now solved see demo or update code
