### ISSUE TITLE
[Feature Request] Allow Text Entry In Idea Number Field

### ISSUE THREAD

**Issue by royaltongue** [icbestCA/giftmanager#25]
I was just using the website on mobile and felt that dragging items was hard on a smaller screen. 

Would it be possible to allow clicking the idea number and then typing the number in manually?

**Comment by icbestCA** [comment]
Sorry for long time, I've added the feature. Make sure that when you change the ideas priority you also do same for the one it has take. the place.  Ex: 2 become 1, but the previous 1 need to be changed to 2.
