### ISSUE TITLE
OIDC Users Still Need GiftManager Password?

### ISSUE THREAD

**Issue by royaltongue** [icbestCA/giftmanager#29]
After realizing my incredibly stupid mistake in setting up OIDC (sorry about that by the way ;P ), I finally got it set up.

Anyway, I noticed that users registered through OIDC are still required to set up a GiftManager password. Also, users created this way can still log in using the default form. Ideally, I think OIDC users should only be able to log in through OIDC, otherwise the added security doesn't really matter anymore.

Even better, a way to disable to default login form completely and only show the OIDC login button. That way I could make sure that Authentikw as the only way in

EDIT: Also thank you again for all the work!

**Comment by icbestCA** [comment]
Sure, I hadn’t thought of that feature as a security measure, but as you mentioned, it does make sense to disable the default login. I’ll work on adding that this weekend, along with a way to store the .env file in the data folder for Docker.

**Comment by icbestCA** [comment]
Hello, I made a new release, make sure you check it out, it has more informations, but here the most of it.

**Disable Default Login Form**: Set ENABLE_DEFAULT_LOGIN=false in the .env file. This will disable the password-based login form and only show the OIDC login option.

**.env File Location:** The .env file is now stored in the /data folder (mounted with Docker), ensuring it's preserved during container updates. If missing, a default file will be generated.
Thanks.
