### ISSUE TITLE
SHA1 Depreciated for Password Hashing

### ISSUE THREAD

**Issue by Robert-litts** [icbestCA/giftmanager#3]
Saw that SHA-1 is being used for hashing passwords, which is insecure, as stated in the warning in [hashlib](https://docs.python.org/3/library/hashlib.html): _"Warning: Some algorithms have known hash collision weaknesses (including MD5 and SHA1). Refer to [Attacks on cryptographic hash algorithms](https://en.wikipedia.org/wikiCryptographic_hash_function#Attacks_on_cryptographic_hash_algorithms) and the [hashlib-seealso](https://docs.python.org/3/library/hashlib.html#hashlib-seealso) section at the end of this document._

Additionally: _"Warning: Salted hashing (or just hashing) with BLAKE2 or any other general-purpose cryptographic hash function, such as SHA-256, is not suitable for hashing passwords."_

Alternative approach could be to utilize [hashlib.pbkdf2_hmac](https://docs.python.org/3/library/hashlib.html#hashlib.pbkdf2_hmac) if you want to stick with the hashlib library or shift over to [argon2](https://pypi.org/project/argon2-cffi/) password hashing function.

**Comment by icbestCA** [comment]
Now using Argon2 thanks to the help from [Robert-litts](https://github.com/Robert-litts).
