### ISSUE TITLE
[Bug] Cannot Delete Default Profiles With OIDC User

### ISSUE THREAD

**Issue by royaltongue** [icbestCA/giftmanager#30]
When trying to remove the default profiles, it asks for the user's password. I tried using my Authentik password directly, but unsurprisingly that didn't work.

**Comment by icbestCA** [comment]
Yeah, sorry didn't think about that.  Now solved in release v1.1.1 , no need to password now, just go to `/delete_default_profiles` to delete them and **gain the admin status for you.**
