### ISSUE TITLE
Feature Request: Households/Viewing permission

### ISSUE THREAD

**Issue by Eschguy** [icbestCA/giftmanager#32]
Between my wife and I, we have, due to divorce, four households (my mom, my dad, her mom, her It would be nice if we could say people in the "Her Dad" group could only see others in "Her Dad" group, but not in others. My Father-in-law doesn't need to see mother-in-law's wishlist, and vice versa.

**Comment by icbestCA** [comment]
Yeah, I was already thinking that, I will implement it this week. It will probably be a page with checkbox and groups to select people. Thanks for the idea.

**Comment by icbestCA** [comment]
Hello, I've added the feature, just need to go at `/families` to manage the groups. 
Here the basic for the management:
1. Add groups using the form, enter the name and select the users you want in it.
          **You **must at least select one user** when creating the group, when a group is empty, it is deleted.
2. Using the checkbox you can select the users in each groups.

_**Important**_
- A user with no group can be seen by everyone and he can see everyone.
- Only an admin can access the page.
- The users in different groups can still be accessed with the URL, but cannot be viewed with the app interface.
- Make sure to save changes after updating the permissions grid.
- A user can be in multiple groups.
See version v1.2.0
Tell me if it's good for you.

**Comment by Eschguy** [comment]
Despite having `"admin": true,` in `users.json` for my account, I'm unable to see the /families page.

**Comment by Eschguy** [comment]
Just wanted to update, this seems to meet the needs I was needing.
