### ISSUE TITLE
Bug: fails to start

### ISSUE THREAD

**Issue by Eidenz** [icbestCA/giftmanager#7]
Just started the docker image and instantly got this crash:
```
Traceback (most recent call last):
  File "/app/app.py", line 31, in <module>
    users = json.load(file)
            ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 17 column 2 (char 596)
```

I would guess you're missing some kind of check to see if the file exists before reading it on first launch?

**Comment by icbestCA** [comment]
Thanks, I've found, it is in the users.json    
{
        "username": "user2",
        "password": "$argon2id$v=19$m=65536,t=3,p=4$IZfmO/VxTL1wm/+arwqJrA$dtH8cONMraVIDYFdhypcdOoTbH4e4DjeJ8QH5pnw3+Y",
        "full_name": "User Two",
        "birthday": "2028-01-28",
        "last_name": "Two",
        "email": "user2@example.com"    <----------------    this line was missing a comma.
	"avatar": "icons/avatar2.png"
    }
Thanks for the report i've recompiled and pushed the docker image.
