### ISSUE TITLE
[BUGS] Users return upon container restart.

### ISSUE THREAD

**Issue by geraveoyomama** [icbestCA/giftmanager#9]
The issues I run into is that the demo users are deleted and custom users can be added, but when the container is stopped and started the original demo users return and /setup is not accessible on http://127.0.0.1:5000/setup.

When running in a container like so:

```oci@server:~$ podman run -p 5000:5000 icbest/giftmanager:latest
 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.0.2.100:5000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 394-483-947
10.0.2.100 - - [25/Aug/2024 14:39:34] "GET /dashboard HTTP/1.1" 200 -
10.0.2.100 - - [25/Aug/2024 14:39:35] "GET /static/icons/help.svg HTTP/1.1" 304 -
10.0.2.100 - - [25/Aug/2024 14:39:35] "GET /static/icons/cart.svg HTTP/1.1" 304 -
10.0.2.100 - - [25/Aug/2024 14:39:35] "GET /static/icons/mail.svg HTTP/1.1" 304 -
10.0.2.100 - - [25/Aug/2024 14:39:35] "GET /static/icons/avatar2.png HTTP/1.1" 304 -
10.0.2.100 - - [25/Aug/2024 14:39:35] "GET /static/icons/log-out.svg HTTP/1.1" 304 -
10.0.2.100 - - [25/Aug/2024 14:39:35] "GET /static/icons/avatar1.png HTTP/1.1" 304 -
10.0.2.100 - - [25/Aug/2024 14:39:41] "GET /add_user HTTP/1.1" 200 -
10.0.2.100 - - [25/Aug/2024 14:39:41] "GET /static/icons/avatar1.png HTTP/1.1" 304 -
10.0.2.100 - - [25/Aug/2024 14:39:41] "GET /static/icons/avatar2.png HTTP/1.1" 304 -
10.0.2.100 - - [25/Aug/2024 14:39:41] "GET /static/icons/avatar3.png HTTP/1.1" 304 -
10.0.2.100 - - [25/Aug/2024 14:39:41] "GET /static/icons/avatar5.png HTTP/1.1" 304 -
10.0.2.100 - - [25/Aug/2024 14:39:41] "GET /static/icons/avatar4.png HTTP/1.1" 304 -
10.0.2.100 - - [25/Aug/2024 14:39:41] "GET /static/icons/avatar6.png HTTP/1.1" 304 -
10.0.2.100 - - [25/Aug/2024 14:39:56] "POST /add_user HTTP/1.1" 302 -

**Comment by icbestCA** [comment]
I will check on my side, but it seems that changes aren't saved to the json, I know Flask run primarily in Ram, maybe there's writing permission missing for the JSON?

**Comment by geraveoyomama** [comment]
ok alrighty, since restarting with this command `podman run -d --replace --name gift-manager --publish 5000:5000/tcp --annotation run.oci.keep_original_groups=1  --userns keep-id --volume app:/app:Z docker.io/icbest/giftmanager:latest`
and running with `--volume app:/app:Z` omitted I get one with custom users and one without custom users respectively

**Comment by geraveoyomama** [comment]
got a message!

`PermissionError: [Errno 13] Permission denied: 'users.json'`

**Comment by geraveoyomama** [comment]
after setting `rw,z` on the volume and manually editing the users.json to remove the trial users it is showing up correctly

**Comment by geraveoyomama** [comment]
`podman run -d --replace --name gift-manager --publish 5000:5000/tcp --volume app:/app:rw,Z docker.io/icbest/giftmanager:latest`

is a working command with persistent storage in the podman `app` volume

after editing `users.json`

**Comment by icbestCA** [comment]
Thanks, didn't used Podman, but glad you were to solved it.
